### ISSUE TITLE
0.25 case doesnt wasnt to work

### ISSUE THREAD

**Issue by vcprando** [mom-ocean/MOM5#116]
[vpr561@raijin3 exp]$ ./MOM_run.csh --platform nci --type MOM_SIS --experiment global_0.25_degree_NYF --download_input_data
Traceback (most recent call last):
  File "./get_exp_data.py", line 8, in <module>
    import argparse
ImportError: No module named argparse
cp: cannot stat `global_0.25_degree_NYF.input.tar.gz': No such file or directory
tar (child): global_0.25_degree_NYF.input.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR: the experiment directory '/short/v45/vpr561/mom/work/global_0.25_degree_NYF/INPUT' does not exist or does not contain input and preprocessing data directories!
Either use the --download_input_data option or copy the input data from the MOM data directory manually.
To manually dowload the data execute the following:
cd /short/v45/vpr561/mom/data
./get_exp_data.py global_0.25_degree_NYF.input.tar.gz
mkdir -p /short/v45/vpr561/mom/work
cp archives/global_0.25_degree_NYF.input.tar.gz /short/v45/vpr561/mom/work
cd /short/v45/vpr561/mom/work
tar zxvf global_0.25_degree_NYF.input.tar.gz
[vpr561@raijin3 exp]$

**Comment by vcprando** [comment]
[vpr561@raijin3 exp]$ ./MOM_run.csh --plataform nci --type MOM_SIS --experiment global_0.25_degree_NYF --download_input_datagetopt: unrecognized option '--plataform'
Error: destination /short/v45/vpr561/mom/data/archives/global_0.25_degree_NYF.input.tar.gz already exists.
/short/v45/vpr561/mom/data
cp: cannot stat `global_0.25_degree_NYF.input.tar.gz': No such file or directory
tar (child): global_0.25_degree_NYF.input.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR: the experiment directory '/short/v45/vpr561/mom/work/global_0.25_degree_NYF/INPUT' does not exist or does not contain input and preprocessing data directories!
Either use the --download_input_data option or copy the input data from the MOM data directory manually.
To manually dowload the data execute the following:
cd /short/v45/vpr561/mom/data
./get_exp_data.py global_0.25_degree_NYF.input.tar.gz
mkdir -p /short/v45/vpr561/mom/work
cp archives/global_0.25_degree_NYF.input.tar.gz /short/v45/vpr561/mom/work
cd /short/v45/vpr561/mom/work
tar zxvf global_0.25_degree_NYF.input.tar.gz

**Comment by aekiss** [comment]
Closing - I'm guessing after 5 years this issue is now irrelevant to current configurations...
