### ISSUE TITLE
FMS submodule

### ISSUE THREAD

**Issue by aidanheerdegen** [mom-ocean/MOM5#179]
Currently the FMS code is inserted into the MOM5 codebase manually.

Having FMS as a submodule would allow for easier updating to new versions of FMS. We can also rebase our local changes on to new versions.

**Comment by aekiss** [comment]
@aidanheerdegen is this issue moot now that FMS is a subtree (PR https://github.com/mom-ocean/MOM5/pull/296)?

**Comment by aidanheerdegen** [comment]
Yeah.
