### ISSUE TITLE
mppnccombine does not detect bad command line options

### ISSUE THREAD

**Issue by aidanheerdegen** [mom-ocean/MOM5#180]
mppnccombine will fail silently when given a command line option that it does not recognise. It does not fail with an error condition.

This is bad, as it makes it difficult to diagnose when there is a typo in a config file or command line, or the user has an older version of mppnccombine in their path that does not support some of the newer features, e.g. netcdf4 output and file compression.

**Comment by marshallward** [comment]
What is the return code?  Is mppnccombine reporting the failure?  Or is payu ignoring it?

**Comment by aidanheerdegen** [comment]
Returns zero. I've put in a fix.

**Comment by marshallward** [comment]
NM, saw the patch.

**Comment by marshallward** [comment]
Thought this was a payu issue, sorry...

**Comment by aidanheerdegen** [comment]
Merged into master. Fixed.
