### ISSUE TITLE
Add checksums for incoming ice ocean boundary values

### ISSUE THREAD

**Issue by nicjhan** [mom-ocean/MOM5#182]
This issue will add checksums for incoming coupling fields. For the time being we do this in access_coupler/ocean_solo.F90 however it should be easy to move to other drivers.

**Comment by arnoldsu** [comment]
Not sure what I am doing but just show what we have changed. Line before: **call update_ocean_model**

#ifdef ACCESS
     do_sfix_now = .false.
     !write(stdoutunit,*) 'XXX: in ocean_solo, dt_cpld = ', dt_cpld
     int_sec = (nc-1) * dt_cpld
     !write(stdoutunit,*) 'XXX: in ocean_solo, nc, int_sec, sfix_hours = ',nc, int_sec, sfix_hours
     !if (mod(int_sec,sfix_hours*3600) == 0 .and. nc /= 1) do_sfix_now = .true.
     if (mod(int_sec,sfix_hours*3600) == 0 ) do_sfix_now = .true.
#endif

     call update_ocean_model(Ice_ocean_boundary, Ocean_state, Ocean_sfc, Time, Time_step_coupled)

**Comment by nicjhan** [comment]
Thanks a lot @arnoldsu. I'll put this in too. Actually I'm going to talk to Peter about making sure that we have all your changes (and vice-versa).

**Comment by arnoldsu** [comment]
take it slowly cuz our versions have diverted since two years ago. so might need to check it before add it. I have ask Fabio to help me to test based on your version.
