### ISSUE TITLE
Large default chunking in 1D record dimension variables

### ISSUE THREAD

**Issue by aidanheerdegen** [mom-ocean/MOM5#195]
@russfiedler reported:

> I'm wondering if anybody knows what's going on here. It looks like record dimension variables get a chunksize of 524288 but if there's any other
> 
> dimension for the variable chunking is reduced to 1 along the unlimited dimension. The result is that you get ludicrous file sizes for simple time series. For instance look at /g/data3/hh5/tmp/cosima/access-om2/1deg_jra55_ryf_spinup8/output000/ocean/ocean_scalar.nc
> 
> There's 4 variables with chunking of 4MB each bloating the file seriously.
> 
> 
>        double time(time) ;
>                     time:long_name = "time" ;
>                     time:cartesian_axis = "T" ;
>                     time:calendar_type = "NOLEAP" ;
>                     time:calendar = "NOLEAP" ;
>                     time:bounds = "time_bounds" ;
>                     time:units = "days since 0001-01-01 00:00:00" ;
>                     time:_Storage = "chunked" ;
>                     time:_ChunkSizes = 524288 ;
> 
> but
> 
>                 float ke_tot(time, scalar_axis) ;
>                     ke_tot:long_name = "Globally integrated ocean kinetic energy" ;
>                     ke_tot:units = "10^15 Joules" ;
>                     ke_tot:valid_range = 0.f, 1.e+20f ;
>                     ke_tot:missing_value = -1.e+20f ;
>                     ke_tot:_FillValue = -1.e+20f ;
>                     ke_tot:cell_methods = "time: mean" ;
>                     ke_tot:time_avg_info = "average_T1,average_T2,average_DT" ;
>                     ke_tot:_Storage = "chunked" ;
>                     ke_tot:_ChunkSizes = 1, 1 ;
> 
> The only thing I can see is some chunksize cache setting in the creation of files. I didn't think this affected the variables in the file though.
> 
>              error=NF__CREATE( trim(mpp_file(unit)%name), IOR(NF_NETCDF4,NF_CLASSIC_MODEL), inital, fsize, mpp_file(unit)%ncid )
> 
> but I can't find any calls to NF_DEF_VAR_CHUNKING which is the usual way to do this. And why the lack of chunking for ke_tot etc?
> 
> I can't reproduce the behaviour with nf90 calls. Is it something with the F77 interface or am I missing something?
>

**Comment by aidanheerdegen** [comment]
Hi Russ,

Looks to be a netcdf library related error.

With `netcdf/4.3.3.1` if I do this:

	ncdump -h /g/data3/hh5/tmp/cosima/access-om2/1deg_jra55_ryf_spinup8/output000/ocean/ocean_scalar.nc > tmp.cdl
	ncgen -k 4 tmp.cdl

It produces this:

	ncdump -hs tmp.nc | grep -i chunk | grep time

		time:_Storage = "chunked" ;
		time:_ChunkSizes = 524288 ;
		time_bounds:_Storage = "chunked" ;
		time_bounds:_ChunkSizes = 1, 2 ;


With `netcdf/4.2.2.1`:

	ncgen -k 4 tmp.cdl
	ncdump -hs tmp.nc | grep -i chunk | grep time
		time:_Storage = "chunked" ;
		time:_ChunkSizes = 1 ;
		time_bounds:_Storage = "chunked" ;
		time_bounds:_ChunkSizes = 1, 2 ;


A netcdf library change in `nci.environs` will knock this on the head (`netcdf/4.3.2` has the same bad problem)

Cheers

Aidan

**Comment by russfiedler** [comment]
[http://www.unidata.ucar.edu/software/netcdf/docs/netcdf_perf_chunking.html](url)

Indicates that the chunking should be 4KiB or 512 elements.

**Comment by russfiedler** [comment]
Ok this is the state of play. There's been an evolution of default chunking strategies for variables of purely unlimited dimension (for example Time).

Pre 4.3.2   purely unlimited dimension variables are written in chunks of 1 element long
From 4.3.2 to 4.3.3.1 chunking is 4MiB
From 4.4.0 chunking is 4KiB

Note that this won't affect time series variables like global averages since they have a supplementary axis " scalar_axis".

If users have linked using 4.3.3.1 they should check for anomalously large files and probably rechunk usiing **nccopy** .

**Comment by marshallward** [comment]
I'll ask if we can get 4.4.1.1 installed for general use.
