### ISSUE TITLE
/preprocessing/regrid => NetCDF: Start+count exceeds dimension bound

### ISSUE THREAD

**Issue by sklee621** [mom-ocean/MOM5#207]
Hi,

I am a new user of MOM5. I am trying to use /mom/src/preprocessing/regrid to regrid chl file from one tripole to another tripole grid. The program compile and run. But, I get the following error message
=>
FATAL: error in putting chl in file chl.nc: NetCDF: Start+count exceeds dimension bound

I found a following discussion on the same issue with regrid_3d
=>
https://groups.google.com/forum/#!searchin/mom-users/Start$2Bcount$20exceeds$20dimension$20bound%7Csort:date/mom-users/hW6UZnZEfak/5mmhI-MFvigJ

It appears that the problem is something to do with allocations.... Any help would be appreciated. 

Sang-Ki

**Comment by nicjhan** [comment]
Russ said: Russ Fiedler [4:47 PM]
@nic (or someone) Could you close this one? https://github.com/mom-ocean/MOM5/issues/207 The user solved it themselves according to the MOM5 email list.
