### ISSUE TITLE
Incorporate Jochum 2009 background diffusivity

### ISSUE THREAD

**Issue by aidanheerdegen** [mom-ocean/MOM5#219]
The ACCESS-CM2 fork implemented the Jochum 2009 background diffusivity

https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2008JC005030

Fabio needs this integrated into the main MOM5 branch ASAP, and can't wait until the CM2 code harmonisation process is finished.

**Comment by aidanheerdegen** [comment]
An small 1 degree test run shows the following spatial pattern for `diff_cbt_j09`

![figure_1](https://user-images.githubusercontent.com/6063709/40336944-e0f6735e-5daf-11e8-9861-cd669569b5b0.png)

And a section at x = -166.5 deg shows the functional form (which is the same for all depths)

![figure_2](https://user-images.githubusercontent.com/6063709/40336961-03b8e8cc-5db0-11e8-8570-c6648ae09572.png)

**Comment by aidanheerdegen** [comment]
I have tried, with no success, to compare this to the ACCESS-CM2 background diffusivity correction. Because of the way it is coded in CM2 fork there is no way to diagnose it directly, although I am happy to hear opinions to the contrary.

@russfiedler are we happy with the numbers in the plots and the form of the correct? Fabio is keen to try it out, so I'll merge it if it is deemed to be ok.

**Comment by russfiedler** [comment]
@aidanheerdegen  Yep, they look correct. Goes from 1e-6 to 1e-5 with the correct looking profile. If you do a run with all the other vertical mixing you should see these values as a lower bound everywhere.

**Comment by aidanheerdegen** [comment]
Yeah I tried that but had some trouble getting the correct field to be spat out using the diag_table. I'll try one more time

**Comment by aidanheerdegen** [comment]
So `diff_cbt` isn't a diagnostic. This is annoying.

**Comment by aidanheerdegen** [comment]
I've output `diff_cbt_s` and `diff_cbt_t` but I'm not sure what use that is

**Comment by aidanheerdegen** [comment]
I'm confident the new code is doing the same as the old CM2 code, and the number difference is due to a namelist option in the CM2 run:
```
app/mom/rose-app.conf:background_diffusivity=0.5e-5
```
I was planning on setting a similar value for the MOM-SIS run to make absolutely sure they are the same. But I'm unsure how to proceed. Dave's code used `background_diffusivity` in `ocean_vert_tidal.F90`. Russ' changes specify
```fortran
!                j09_bgmin is background diffusivity at the equator
!                j09_bgmax is background diffusivity >= j09_lat```
So `j09_bgmax` is the equivalent of `background_diffusivity` in `ocean_vert_tidal`. I think it is undesirable to effectively have the same quantity defined in two places as they can get out of sync if it is changed in one place and not the other.

Do we import the `background_diffusivity` value from `ocean_vert_tidal` and use that?

**Comment by russfiedler** [comment]
Agreed with you on the difference. `background_diffusivity` in `ocean_vert_tidal.F90` is only there as a last resort to account for cases when there are no backgrounds provided by other schemes (or you want to add more for some obscure reason). It should be set to zero whenever a scheme has set the background. I don't know why the default in `ocean_vert_tidal.F90` is non zero but we'll have to leave it there or we'll potentially break people's experiments. Just set it to zero in the namelist for proper runs but for the test run you may have to set it to 0.5e-5 since it was double counting from what I can tell.

**Comment by russfiedler** [comment]
Looks good.

**Comment by aidanheerdegen** [comment]
The following namelist options are required to replicate above behaviour:
```fortran
&ocean_vert_mix_nml    
   j09_diffusivity = .true.
    j09_bgmin       = 1.0e-6
    j09_bgmax       = 0.5e-5
    j09_lat         = 20.0
/
&ocean_vert_tidal_nml
  background_diffusivity=0.0
/
```
(In addition to any other options you may have in those namelists)

**Comment by aidanheerdegen** [comment]
I have confirmed `background_diffusivity=0.0` is necessary.

I set background_diffusivity=`1.0e-5` and this is the result:

![figure_6](https://user-images.githubusercontent.com/6063709/40526916-e294650c-602c-11e8-9177-1ff332de245e.png)

The `background_diffusivity` has been added to the `j09_diffusivity`
