### ISSUE TITLE
redsea gulf bay fix is too slow

### ISSUE THREAD

**Issue by aidanheerdegen** [mom-ocean/MOM5#244]
The fix used in the 1 deg coupled model to ensure the red sea does not get too saline (`redsea_gulfbay_sfix`) is poorly written and consequently consumes a large percentage of the runtime.

The time also blows out with increases in vertical levels.

As this is used in ACCESS-CM and ACCESS-ESM1.5 it needs to be fixed

**Comment by aidanheerdegen** [comment]
@russfiedler and @marshallward. You guys suggested there was a relatively easy fix for this.

First up, do we know how much time it consumes? I know Kial found it started to increase at 75 vertical levels and dominated run time at greater than 100 vertical levels.

Does anyone want to put up their hand to rewrite it?

**Comment by aidanheerdegen** [comment]
This is the 1 degree ACCESS-OM2-1degree timing for default `sfix_hours`
```
                                          tmin          tmax          tavg          tstd  tfrac grain pemin pemax
Total runtime                       147.132441    147.265488    147.224698      0.031142  1.000     0     0   215
Ocean                               111.094157    112.828801    112.426662      0.244312  0.764     1     0   215
(Ocean initialization)                4.273902      4.341281      4.308422      0.013383  0.029    11     0   215
(Ocean ODA)                           0.000000      0.000000      0.000000      0.000000  0.000    11     0   215
(Red Sea/Gulf Bay salinity fix)      27.551600     28.652322     28.407015      0.198776  0.193    31     0   215
```
So the redsea fix is taking 24% of the ocean time, and 18% of total runtime. The first stat is the most important, as this is usually run 1 year at a time, so the ocean portion of the runtime will dominate over the intialisation, and the total runtime also includes some time waiting on the ice model.

**Comment by marshallward** [comment]
My timings, before:
```
Total runtime                       158.475062    158.585138    158.547413      0.023115  1.000     0     0   215
Ocean                               135.480436    136.895652    136.117239      0.321816  0.859     1     0   215
(Ocean initialization)                2.635438      2.698445      2.668143      0.012028  0.017    11     0   215
(Ocean ODA)                           0.000000      0.000000      0.000000      0.000000  0.000    11     0   215
(Red Sea/Gulf Bay salinity fix)      39.118928     40.048965     39.771429      0.186311  0.251    31     0   215
```
After:
```
Total runtime                       109.968194    110.067674    110.019217      0.021781  1.000     0     0   215
Ocean                                95.220443     96.201307     95.578058      0.237256  0.869     1     0   215
(Ocean initialization)                1.635478      1.689457      1.667267      0.009894  0.015    11     0   215
(Ocean ODA)                           0.000000      0.000000      0.000000      0.000000  0.000    11     0   215
(Red Sea/Gulf Bay salinity fix)       0.003657      0.018841      0.007726      0.002939  0.000    31     0   215
```

**Comment by marshallward** [comment]
Probably fairly self-evident at this point... but profiling shows that it was the `mpp_global_field` functions consuming (or barriering) all of the time here

**Comment by marshallward** [comment]
Is it not OK?  Your runtime was ~111 sec with ~30 sec of redsea/gulf mixing.  Now that it's dropped to something negligible, it's down to about ~80 sec.

Your differences from my numbers would be due to my Score-P overhead.

**Comment by marshallward** [comment]
Here is the diff between the versions after 24 hours (applied at the 12 hour mark), which (correctly?) only appear along halo boundaries.
![redsea_fast_1day](https://user-images.githubusercontent.com/462315/45606549-60ac7180-ba89-11e8-8a89-fafbb7237ecd.png)

And just for reference, here is a diff with the mixing off and on:
![redsea_diff_1day](https://user-images.githubusercontent.com/462315/45606548-6013db00-ba89-11e8-928e-dddb27520c9a.png)

**Comment by aidanheerdegen** [comment]
Confirming Marshall’s result. Ran the model from 1 Jan for 1 month, set `sf_hours=720`, and output salt field daily. Subtracted the control run with no red sea fix. This should show the effect of the red sea fix. Then subtracted this difference field from the old code from the same difference field from the new code. Would expect them to be very similar

![figure_1](https://user-images.githubusercontent.com/6063709/45607205-1bd70980-ba8e-11e8-8bf7-eb704256c414.png)

**Comment by russfiedler** [comment]
The discrepancy comes about from using `Ocean_sfc` to get a data domain. `Ocean_sfc` has no halos therefore it is the same as the compute domain and there a no further halo updates for salt within the main loop which is not what is expected.

**Comment by aidanheerdegen** [comment]
I'll merge https://github.com/mom-ocean/MOM5/pull/247 now. A full comparison to the CM2 code will have to wait until CM2 harmonisation is complete.
