### ISSUE TITLE
Print out MOM executable version of git hash on start-up

### ISSUE THREAD

**Issue by nichannah** [mom-ocean/MOM5#261]
For convenience it would be nice to print out the MOM version of the git hash of it's source on start-up. This will have two benefits: 1) an easy way to connect model output with a particular version of the source code and 2) confirmation that every MOM executable carries it's git hash around with it.

**Comment by aekiss** [comment]
See discussion here: https://github.com/OceansAus/access-om2/issues/31

**Comment by aekiss** [comment]
There was some initial implementation here: https://github.com/aekiss/access-om2/commit/2f368da1f29d04f71158480a4260efbd579aa907
Not sure if that's how you'd like to do it?

**Comment by nichannah** [comment]
That looks good. I found that MOM almost already does this, all I needed to do was to add a print* statement. https://github.com/mom-ocean/MOM5/blob/master/src/shared/version/version.F90.template

Something more thorough like what you propose would be good.

**Comment by aekiss** [comment]
It would be good to have this for CICE, YATM, payu too
