### ISSUE TITLE
FAFMIP inconsistencies with neutral mixing and submesoscale restratification

### ISSUE THREAD

**Issue by russfiedler** [mom-ocean/MOM5#304]
After a month or so @abhisheksavita and I have tracked down some inconsistencies that arise with the masking of fluxes in the neutral mixing and submesoscale code. `T_prog(n)%tmask_limit` is set in `ocean_tracer.F90`
`redist_heat` and `added_heat` both have default min/max as temperature.

1) if we have `tmask_limit_ts_same=.true.` then if either temp or salt is masked then both are masked. The problem arises in the sanity test of no perturbation that `redist_heat` won't get masked by the union with the salt tmask_limit. I guess we should make them all the same in the .true. case but should the mask be based on a union of all three quantities or just the T/S union?

https://github.com/mom-ocean/MOM5/blob/master/src/mom5/ocean_tracers/ocean_tracer.F90#L2857-L2869

2) The `added_heat` tracer has the same default limits as `temp` which is nonsensical. I think the tmask_mask should be identical to either `redist_heat` or `temp`. 

3) Is it even sensible to have different masks for `redist_heat` and `temp` at all? What does FAFMIP protocol have to say about this?

My feeling is to make the redist_heat and added_heat masks the same as temperature.

@StephenGriffies would like your thoughts on what to do.

**Comment by StephenGriffies** [comment]
Good catches @russfiedler  and @abhisheksavita. 

I missed these masks when working through FAFMIP code with @rfarneti .  The masking is ad hoc as it is.  My sense is to do the least harm so long as things are reasonably self-consistent.  Your proposal sounds good.
