### ISSUE TITLE
Bounds mismatch when using extended halos and tides in ocean_barotropic.F90

### ISSUE THREAD

**Issue by russfiedler** [mom-ocean/MOM5#323]
There looks to be a bounds mismatch when using barotropic halos > 1 and applying tidal forcing. This affects both the forcing and the diagnosis of the forcing

https://github.com/mom-ocean/MOM5/blob/master/src/mom5/ocean_core/ocean_barotropic.F90#L6470-L6472

eta_eq_tidal is declared as isd_bt:ied_bt,jsd_bt:jed_bt but Grd%tmask is isd:ied,jsd:jed.

The call to diagnose_2d should pass an array with lower bounds isd and jsd. This means a section should be passed not the whole array.

Currently testing the fixes.

**Comment by adele157** [comment]
Your fixes work great for me Russ. The mask on eta_eq_tidal is fixed, and eta_t no longer has noise.

**Comment by aekiss** [comment]
Great! Thanks @russfiedler - is this bugfix only relevant to runs with tidal forcing?

**Comment by russfiedler** [comment]
Yes, I believe so though there might some other options in that module that haven't been tested with extended halos. Normal halos of extent 1 work fine.
I forgot to mention that the fix involves changing `Grd%tmask(:,:,1)` to `tmask_bt(:,:)`.

@adele157 can you issue a pull request for the changes?

**Comment by aekiss** [comment]
@russfiedler and @adele157 I've merged PR https://github.com/mom-ocean/MOM5/pull/324 so can we close this issue now?
