### ISSUE TITLE
Specifying restart_interval does not work with existing simulation

### ISSUE THREAD

**Issue by aidanheerdegen** [mom-ocean/MOM5#340]
Specifying `restart_interval` does not work with existing simulation because the `restart_interval` is added to `date_init` in the absence of a `ocean_solo.intermediate.res` file.

https://github.com/mom-ocean/MOM5/blob/af3a94d40f21a4b7fd925d13b928f8721ad7d4c8/src/accessom_coupler/ocean_solo.F90#L268-L273

So a `restart_interval` has to be specified that is includes the current model run time. Once this is requires an offset that includes y/m/d and mm/s FMS refuses to calculate that offset: doesn't accept offsets that mix minutes and seconds with with year/month/day.

I think the fix is to change this line

https://github.com/mom-ocean/MOM5/blob/af3a94d40f21a4b7fd925d13b928f8721ad7d4c8/src/mom5/drivers/ocean_solo.F90#L245

from
```fortran
date_restart = date_init
```
to
```fortran
date_restart = date
```

As it is, the work-around is to create a `ocean_solo.intermediate.res` file with the model date, which is effectively the same as the above fix.

**Comment by aidanheerdegen** [comment]
Note this is fixed in the main coupler driver

https://github.com/mom-ocean/MOM5/blob/af3a94d40f21a4b7fd925d13b928f8721ad7d4c8/src/coupler/coupler_main.F90#L1153

but also needs to be fixed in default `ocean_solo.F90` driver

https://github.com/mom-ocean/MOM5/blob/af3a94d40f21a4b7fd925d13b928f8721ad7d4c8/src/mom5/drivers/ocean_solo.F90#L245

and the `accesscm` and `nupoc` drivers

https://github.com/mom-ocean/MOM5/blob/af3a94d40f21a4b7fd925d13b928f8721ad7d4c8/src/accesscm_coupler/ocean_solo.F90#L278

https://github.com/mom-ocean/MOM5/blob/af3a94d40f21a4b7fd925d13b928f8721ad7d4c8/src/mom5/drivers/ocean_solo_nuopc.inc#L446

**Comment by aekiss** [comment]
@aidanheerdegen where is `date` initialised if `ocean_solo.intermediate.res` does not exist?
https://github.com/mom-ocean/MOM5/blob/b8df436/src/accessom_coupler/ocean_solo.F90#L268-L274

I ask because I'm getting this error
`FATAL from PE    71: function set_date_i: Invalid date. Date=0000-00-00 00:00:00`
in a cold start of access-om2 with b8df436 which doesn't occur when I use af3a94d

It seems to be terminating due to failing this check:
https://github.com/mom-ocean/MOM5/blob/b8df436/src/shared/time_manager/time_manager.F90#L2316-L2322

**Comment by aidanheerdegen** [comment]
In `diag_table` IIRC

**Comment by aekiss** [comment]
I have `1900 1 1 0 0 0` in `diag_table` but it's acting like I've set  `0000-00-00 00:00:00` somewhere

**Comment by aidanheerdegen** [comment]
Can you post the full stack trace and the location of your experiment control dir. Tah.

**Comment by aekiss** [comment]
Thanks for taking a look.

Control dir is
`/g/data/v45/aek156/access-om2-build/1deg_jra55_iaf_bgc_test`
and
`/g/data/v45/aek156/access-om2-build/1deg_jra55_iaf_bgc_test/archive/error_logs/access-om2.28834400.gadi-pbs.err`
contains
```
FATAL from PE   213: function set_date_i: Invalid date. Date=0000-00-00 00:00:00


Image              PC                Routine            Line        Source
fms_ACCESS-OM-BGC  0000000001CFB30A  Unknown               Unknown  Unknown
fms_ACCESS-OM-BGC  0000000001855900  mpp_mod_mp_mpp_er          75  mpp_util_mpi.inc
fms_ACCESS-OM-BGC  00000000016EA6DD  time_manager_mod_        3134  time_manager.F90
fms_ACCESS-OM-BGC  00000000004107C1  MAIN__                    306  ocean_solo.F90
fms_ACCESS-OM-BGC  000000000040F662  Unknown               Unknown  Unknown
libc-2.28.so       000014C85B3A6493  __libc_start_main     Unknown  Unknown
fms_ACCESS-OM-BGC  000000000040F56E  Unknown               Unknown  Unknown
```

**Comment by aekiss** [comment]
I'm also using the latest source from libaccessom2 master (https://github.com/COSIMA/libaccessom2/commit/0ab72954ff751e554fa19e9ffd843320f96b704e) but this works with MOM5 af3a94d so seems unlikely to be causing the error in b8df436

**Comment by aekiss** [comment]
https://github.com/mom-ocean/MOM5/commit/b8df436f8acb62cfdcc36d81aa2074d4a43a5f40 also has the FMS update, but (based on a very quick look) I couldn't see anything there that looked like it might explain this error

**Comment by aidanheerdegen** [comment]
I think it is a logic error. Looking at a fix now.
