### ISSUE TITLE
Incorrect documentation for u_surf in surface_flux.F90

### ISSUE THREAD

**Issue by dhruvbhagtani** [mom-ocean/MOM5#348]
`u_surf` is the ice/ocean velocity at the surface. However, in the documentation, it is incorrectly written as the zonal wind velocity at the surface. The mathematics is all correct, it's just the documentation that needs to be changed.

**Comment by navidcy** [comment]
Could you open a PR?

**Comment by aidanheerdegen** [comment]
+1 for the PR

**Comment by dhruvbhagtani** [comment]
Oops. Sorry @navidcy, I forgot about the PR. I'll make one now.

**Comment by dhruvbhagtani** [comment]
Here's the PR: #365.

**Comment by aidanheerdegen** [comment]
There is a neat trick @dhruvbhagtani , if you put "closes #xxx" with the issue number in the description of the PR it will tag the issue and then close it when the PR is merged.
