### ISSUE TITLE
Calendar for interannual forcing

### ISSUE THREAD

**Issue by devasena1964** [mom-ocean/MOM5#362]
Dear MOM5 community,
I am using JRA-55 to run the model for interannual run. The JRA-55 is on Gregorian calendar.
I am saving the outputs in Julian calendar. Model is able to pick the forcing files correctly and I am getting a successful run.

My question is giving input in Gregorian calendar and writing outputs in Julian calendar is correct or not. 
Request some feedback in this regard
Regards
Kalyani

**Comment by aekiss** [comment]
Hi Kalyani,

Why don't you want Gregorian calendar output?

The Gregorian and Julian calendars only differ in that centuries are always leap years in a Julian calendar, and never leap years in Gregorian unless divisible by 400. So the mismatch would only occur occasionally, gaining a 1-day offset in 3 of every 4 centuries (eg 1700, 1800, 1900, but not 2000). Unless you cross such centuries you won't see a difference.

**Comment by devasena1964** [comment]
Dear sir,

actually as per MOM5 guide (https://mom-ocean.github.io/docs/userguide/) I read that Currently, "the FMS time_manager does not support the Gregorian calendar". But when I give inputs in Gregorian calendar MOM code is able to run and complete the run, But the outputs I am writting using Julian calendar. Hence I got the doubt.

this is only doubt, 
since coupler.res has the option of Gregorian, I think I can make one run and check whether it works or not
(Coupler.res)
 2        (Calendar: no_calendar=0, thirty_day_months=1, julian=2, gregorian=3, noleap=4)
  1888     1     1     0     0     0        Model start time:   year, month, day, hour, minute, second
  1959    1     1     0     0     0        Current model time: year, month, day, hour, minute, second

Thank you for your feed back
Regards
Kalyani

**Comment by aidanheerdegen** [comment]
As a follow up, you are forcing the model with ERA5? This is something[ COSIMA are working on](https://github.com/COSIMA/access-om2/issues/242), so we would be interested to hear how you have approached doing this.

**Comment by devasena1964** [comment]
Dear Aidan Heerdegen,
I am using JRA55, not ERA5, I want to check the difference between CORE-IAF and JRA55 how it responds when I am simulating a global model simulation and what type of changes occurring in the biochemistry of Indian Ocean. 

Coming to approach, I just downloaded  the JRA55 forcing files from website and now trying to set up the run initially on one  degree global run.
RegardsKalyani
    On Tuesday, February 1, 2022, 11:23:38 AM GMT+5:30, Aidan Heerdegen ***@***.***> wrote:  
 
 


As a follow up, you are forcing the model with ERA5? This is something COSIMA are working on, so we would be interested to hear how you have approached doing this.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aekiss** [comment]
Hi Kalyani, do you mean JRA55-do, not JRA55?
-Andrew

**Comment by devasena1964** [comment]
HelloI am using JRA-55 and able to run the modelThank youRegardsKalyani

Sent from Yahoo Mail on Android 
 
  On Tue, 1 Feb 2022 at 15:13, Andrew ***@***.***> wrote:   


Hi Kalyani, do you mean JRA55-do, not JRA55?
-Andrew

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aekiss** [comment]
JRA55-do (not JRA55) is the dataset that's intended to replace CORE

**Comment by devasena1964** [comment]
Hello sir,Thank you for your inputRegardsKalyani

Sent from Yahoo Mail on Android 
 
  On Wed, 2 Feb 2022 at 3:53, Andrew ***@***.***> wrote:   


JRA55-do (not JRA55) is the dataset that's intended to replace CORE

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aidanheerdegen** [comment]
Sorry. It is quite clear in your comment you are not using ERA5, not sure why I managed to get confused. Thanks for clearing that up for me.

**Comment by devasena1964** [comment]
Dear Sir,I am using JRA55-do only, which I have downloaded from https://esgf-node.llnl.gov and used mom fregrid tools to bring to one deg global for running the model.
 Thank you very much
RegardsKalyani

    On Wednesday, February 2, 2022, 03:53:49 AM GMT+5:30, Andrew Kiss ***@***.***> wrote:  
 
 


JRA55-do (not JRA55) is the dataset that's intended to replace CORE

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
