### ISSUE TITLE
OpenMP support not working (MOM_SIS)

### ISSUE THREAD

**Issue by puneet336** [mom-ocean/MOM5#366]
Hi, 
I tried compiling the mom5 code (MOM_SIS) with openmp support. But i am unable to see threads at runtime.
the compilation logs are - 
https://github.com/puneet336/MOM5/blob/main/logs01
in summary, as i am using intel compilers -  i have ensured that all files are compiled using -qopenmp flag.

If i launch the code using 
OMP_NUM_THREADS=4
mpirun -np 512 -ppn 32  fms_MOM_SIS.x 

but unable to see threads on compute nodes. I have attached the links to compilation logs.

Could you please advice if i need to add any additional flag/ modifications to enable the openMP support during runtime?

**Comment by russfiedler** [comment]
Hi, as mentioned on the google group, OpenMP is not supported in MOM5 and there are no plans to support it.

**Comment by puneet336** [comment]
Thank you,
one final query i have is that does the  MOM5 support pnetcdf? i noticed 
```
&mpp_io_nml
parallel_netcdf = .true.
pnetcdf = .true.
```
from here - http://cosima.org.au/wp-content/uploads/2018/06/COSIMA2018-Yang_Rui.pdf

**Comment by aidanheerdegen** [comment]
Hi @puneet336 

I'm afraid we haven't merged those changes into our FMS fork. They available as a separate branch on the main FMS repo

https://github.com/NOAA-GFDL/FMS/tree/with-parallel-netcdf

I have made an issue to include this in our FMS fork

https://github.com/mom-ocean/FMS/issues/8
