### ISSUE TITLE
Cycle4 diagnostic wdet100 is incorrect

### ISSUE THREAD

**Issue by hakaseh** [mom-ocean/MOM5#379]
@aekiss I just found out that I incorrectly calculate `wdet100` (detritus export at 100 m).
I fixed this now and push to my own branch: https://github.com/hakaseh/mom/commit/e44298846ac358d760b73c6f0d2e997d7a610059
This error only affects the diagnostic `wdet100` saved for `cycle4` and `IAMIP2`. Instead of detritus export at 100 m, it represents detritus export at the uppermost ocean layer. Hence, `wdet100` can be deleted I think.

**Comment by aekiss** [comment]
Thanks for spotting this - I've added it to the errata [here](http://cosima.org.au/index.php/2020/07/29/data-available-0-1-1958-2018-access-om2-iaf-run/). Might be good to also contact Chloe to find out how to flag/retract the IAMIP2/OMIP2 data.

I'll merge it if you do a PR.

**Comment by hakaseh** [comment]
Thanks for adding `wdet100` to the errata. 
I noticed the fourth bullet point of the errata says "linear mortality" but this should be "grazing". 
`wdet100` or `NPP` does not affect OMIP output because for OMIP `wdet100` was post-processed from 3D detritus output and `pprod_gross` was considered `NPP`.
I'll do a PR by tomorrow.

**Comment by aekiss** [comment]
Thanks @hakaseh - well spotted, I've fixed the errata. Maybe we need errata for the errata 😄 

Glad to hear the OMIP data is unaffected.
